# Generated by Django 4.2.7 on 2023-11-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0003_alter_exercise_id_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='ID',
            field=models.IntegerField(db_column='exercise_id', primary_key=True, serialize=False),
        ),
    ]
