# Generated by Django 4.2.7 on 2023-11-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0004_alter_exercise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='ID',
            field=models.AutoField(db_column='exercise_id', primary_key=True, serialize=False),
        ),
    ]
