# Generated by Django 4.2.7 on 2023-11-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0006_musclegroup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musclegroup',
            table='muscle_group',
        ),
    ]
