# Generated by Django 4.2.7 on 2023-11-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0007_alter_musclegroup_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musclegroup',
            table='group_muscle',
        ),
    ]
