# Generated by Django 4.2.7 on 2023-11-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0009_remove_musclegroup_id_musclegroup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('muscle_id', models.AutoField(db_column='muscle_id', primary_key=True, serialize=False)),
                ('muscle_name', models.CharField(db_column='muscle_name', max_length=70)),
                ('group_id', models.CharField(db_column='group_id', max_length=50)),
            ],
            options={
                'db_table': 'muscle',
            },
        ),
    ]
