# Generated by Django 4.2.7 on 2023-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0010_muscle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('ID', models.AutoField(db_column='machine_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='machine_name', max_length=50)),
            ],
            options={
                'db_table': 'machine',
            },
        ),
    ]
