# Generated by Django 4.2.7 on 2023-11-08 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0011_machine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='Name',
            new_name='exercise_name',
        ),
        migrations.AddField(
            model_name='exercise',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_database.machine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_database.muscle'),
            preserve_default=False,
        ),
    ]
