# Generated by Django 4.2.7 on 2023-11-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0013_remove_muscle_group_id_muscle_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle',
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_database.exercise')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_database.muscle')),
            ],
            options={
                'unique_together': {('exercise', 'muscle')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_database.exercise')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_database.machine')),
            ],
            options={
                'unique_together': {('exercise', 'machine')},
            },
        ),
    ]
