# Generated by Django 4.2.7 on 2023-11-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0015_alter_exercisemachine_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muscle',
            old_name='muscle_id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='muscle',
            old_name='muscle_name',
            new_name='name',
        ),
    ]
