# Generated by Django 4.2.7 on 2023-11-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0016_rename_muscle_id_muscle_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisemuscle',
            options={'managed': False},
        ),
    ]
