# Generated by Django 4.2.7 on 2023-11-13 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0017_alter_exercisemuscle_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisemachine',
            name='id',
        ),
        migrations.AddField(
            model_name='exercisemachine',
            name='ID',
            field=models.AutoField(db_column='exercise_machine_id', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
