# Generated by Django 4.2.7 on 2023-11-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0018_remove_exercisemachine_id_exercisemachine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='machines',
            field=models.ManyToManyField(through='test_database.ExerciseMachine', to='test_database.machine'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(through='test_database.ExerciseMuscle', to='test_database.muscle'),
        ),
    ]
