# Generated by Django 4.2.7 on 2023-11-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0019_exercise_machines_exercise_muscles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentLift',
            fields=[
                ('ID', models.AutoField(db_column='current_id', primary_key=True, serialize=False)),
                ('weight', models.FloatField(db_column='max_working_weight', max_length=10)),
                ('reps', models.CharField(db_column='max_reps', max_length=10)),
            ],
            options={
                'db_table': 'current_lift',
            },
        ),
        migrations.CreateModel(
            name='ExerciseDetails',
            fields=[
                ('ID', models.AutoField(db_column='exercise_details_id', primary_key=True, serialize=False)),
                ('intensity', models.CharField(db_column='intensity', max_length=20)),
                ('tips', models.CharField(db_column='tips', max_length=200)),
                ('optimum', models.CharField(db_column='optimum_level', max_length=20)),
                ('link', models.CharField(db_column='picture_video_link', max_length=300)),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_database.currentlift')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_database.exercise')),
            ],
            options={
                'db_table': 'exercise_details',
            },
        ),
    ]
