# Generated by Django 4.2.7 on 2023-11-15 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0022_remove_exercise_exercise_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisedetails',
            name='current',
        ),
        migrations.AddField(
            model_name='currentlift',
            name='exercise_details',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='test_database.exercisedetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisedetails',
            name='current_lift',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_lift', to='test_database.currentlift'),
        ),
    ]
