# Generated by Django 4.2.7 on 2023-11-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0024_remove_exercisedetails_current_lift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlift',
            name='exercise_details',
        ),
    ]
