# Generated by Django 4.2.7 on 2023-11-15 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0025_remove_currentlift_exercise_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlift',
            name='exercise_details',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='test_database.exercisedetails'),
            preserve_default=False,
        ),
    ]
