# Generated by Django 4.2.7 on 2023-11-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0026_currentlift_exercise_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisedetails',
            name='current',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_database.currentlift'),
        ),
    ]
