# Generated by Django 4.2.7 on 2024-01-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0027_alter_exercisedetails_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='currentlift',
            name='exercise_details',
        ),
    ]
