# Generated by Django 4.2.7 on 2024-01-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0028_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisedetails',
            name='intensity',
            field=models.IntegerField(db_column='intensity', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercisedetails',
            name='optimum',
            field=models.IntegerField(db_column='optimum_level', max_length=20),
        ),
    ]
