# Generated by Django 4.2.7 on 2024-01-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_database', '0029_alter_exercisedetails_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisedetails',
            name='intensity',
            field=models.IntegerField(db_column='intensity'),
        ),
        migrations.AlterField(
            model_name='exercisedetails',
            name='optimum',
            field=models.IntegerField(db_column='optimum_level'),
        ),
    ]
